### ISSUE TITLE
Status bar lingering previous text after Count operation

### ISSUE THREAD

**Issue by alankilborn** [Coises/ColumnsPlusPlus#1]
![image](https://user-images.githubusercontent.com/77065706/230775938-cba8d411-b0b1-406e-9490-18e2613146f1.png)

![image](https://user-images.githubusercontent.com/77065706/230775951-de3496d4-6cbb-4c66-8a14-e7707d380f15.png)

Hopefully that's enough info; let me know if not.

**Comment by alankilborn** [comment]
Note:  I built from (unchanged) source, so probably ignore the date in the screenshot.

**Comment by Coises** [comment]
Thank you for your report.

I can't get the same thing to happen here. I think I know what the problem must be... just not why it would occur on some systems but not others. Hopefully commit f826531 will fix this (taking a slightly more "aggressive" approach to clearing the background). Release [v0.0.1.2-alpha](https://github.com/Coises/ColumnsPlusPlus/releases/tag/v0.0.1.2-alpha) has the update.

**Comment by molsonkiko** [comment]
Doesn't happen for me.

**Comment by Coises** [comment]
Closed per remark in https://community.notepad-plus-plus.org/post/85768 that the issue is no longer observed.
