### ISSUE TITLE
Missing dll when trying to run Columns++ 0.7.1-alpha

### ISSUE THREAD

**Issue by astewart77** [Coises/ColumnsPlusPlus#10]
When I upgrade Columns++ from 0.7 to 0.71-alpha, under n++ 8.5.7 Windows 7, I get the message

`The program can't start because api-ms-win-core-realtime-l1-1-1.dll is missing from your computer. Try reinstalling the program to fix this problem.`

Googling Microsoft suggests that this dll was new to Windows 10. I see that the change lines for Column++ include the use of
`QueryInterruptTime`
 which is listed by Microsoft as included in that dll. But I also see some coders referencing use of QueryInterruptTime under Windows 7.

I know n++ isn't formally supporting Windows 7, but is Columns++ moving away from it now? If I have to freeze, I am already very happy with Columns++, but I suspect you have more great code in mind :)

**Comment by Coises** [comment]
@astewart77 Thank you for the clear report, and the kind words. This wasn’t intentional — I just didn’t realize I’d used something that would cause a problem on earlier versions of Windows.

I’ll have to research how to deal with the conflict; there is usually a way to maintain compatibility, and I’ll employ it when I understand it.

**Comment by Coises** [comment]
@astewart77 Would you be willing to try installing the update described here:
https://support.microsoft.com/en-us/topic/update-for-universal-c-runtime-in-windows-c0514201-7fe6-95a3-b0a5-287930f3560c
and let me know if that resolves the problem?

Though I’m not thrilled with the annoyance, I think that if applying a Microsoft update package is all that’s required to support Windows versions that are currently past end-of-life, I’ll document that and consider it a solution.

**Comment by astewart77** [comment]
That link leads to a download of KB2999226 for Win 7 x64. That KB was already installed on my system, but I uninstalled, reinstalled it, rebooted. No change. The update description makes it clear that it enables the Win 10 functions to work on Win 7, but apparently not contained in api-ms-win-core-realtime-l1-1-1.dll.

**Comment by Coises** [comment]
Thank you for trying it. I’m sorry for the aggravation. I’ll try to figure out what is needed.

**Comment by astewart77** [comment]
A bit of handwaving...I don't know what I'm looking for. On my system I have a file
`C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\realtimeapiset.h`
that includes QueryInterruptTime. I don't know how I came to have this Window Kit.

**Comment by Coises** [comment]
Thanks again for your efforts. I think I have a solution, so don’t worry about it further.

It looks like I can replace QueryInterruptTime with GetTickCount64 without any significant effect on the results — timing is pretty much guesswork, anyway; it only has to be close. GetTickCount64 has been available starting with Vista. I’ll make that change and put up a new release soon, probably tomorrow (9/20/2023).

**Comment by Coises** [comment]
Commit [ca9bfe0](https://github.com/Coises/ColumnsPlusPlus/commit/ca9bfe03a4c16d2abd50d564f51b1cf3c2ea9451) / version [0.7.2-alpha](https://github.com/Coises/ColumnsPlusPlus/releases/tag/v0.7.2-alpha) should fix this.

I’ll close now, but will reopen if there is still an issue. Thank you, @astewart77, for identifying the problem so well.
