### ISSUE TITLE
Background Errors from Columns++

### ISSUE THREAD

**Issue by daddel80** [Coises/ColumnsPlusPlus#12]
I have Columns++ running in the background. Occasionally, I receive error messages like these when replacing values in N++. Do these help with troubleshooting? 
![Screenshot1](https://github.com/Coises/ColumnsPlusPlus/assets/53190206/3129916f-5431-4c21-b447-8af4dfcc0bef)

![Screenshot2](https://github.com/Coises/ColumnsPlusPlus/assets/53190206/1fa07f50-7eee-4be2-8d68-dd855370a15d)

**Comment by Coises** [comment]
@daddel80 Can you tell me a little more about what you were doing when this happened? Did you have multiple tabs open? The second view open? Were Columns++ Elastic tabstops enabled in the tab where you were making changes? Were they enabled in any other open tabs? Were these manual replacements in a single tab? “all opened documents” changes? changes made through a plugin?

The information you gave is certainly helpful in knowing where to look; I just don’t know, yet, what to look for or what to try to recreate the error.

**Comment by daddel80** [comment]
Yes, I typically have multiple tabs open at once. The 'Find String in Files' window, or the second view, isn't active. I've disabled the Elastic Tabstop feature, and it's not enabled in other tabs either. If you're referring to editing, I only replaced a single string in one of the tabs. I have added Columns++ into the Main Menue of N++.It was a solitary edit. Indeed, I was testing the MultiReplace Plugin.  I wouldn't know how the plugin could be the cause of the crash. I've also restarted N++ numerous times.
I just want to point out that N++ occasionally returns strings with hex00 via SCI_GETTAG, even when they don't actually exist. While this isn't directly related to the current issue, I think it's important to be aware that N++ can sometimes return unexpected data even with other Commands.
I'll watch the error and look for a pattern. But these crashes don't happen often, so we'll see

**Comment by Coises** [comment]
@daddel80 Thank you for the additional information, and in advance for anything else you can observe. If I can’t reproduce it, would you be willing to replace ColumnsPlusPlus.dll with a diagnostic build of some sort — assuming I can figure out how to prepare one?

**Comment by daddel80** [comment]
Sure! I can replace it with a diagnostic version as often as you'd like. ;) Is there a specific structure that Columns++ establishes and maintains during its runtime? I'm wondering why, even when it's in the background, it still interacts with N++. A dump would be ideal. Well, seems that page needs a look.

**Comment by Coises** [comment]
Plugins get notifications indiscriminately — Notepad++ doesn’t know if a plugin is “in the background”: there isn’t, as far as I can see, such a concept as “in the background.” It’s up to each plugin to return as quickly as possible from notifications it doesn’t need.

Notification codes 2007 and 2008 are [SCN_UPDATEUI](https://www.scintilla.org/ScintillaDoc.html#SCN_UPDATEUI) and [SCN_MODIFIED](https://www.scintilla.org/ScintillaDoc.html#SCN_MODIFIED). Columns++ watches those to implement Elastic tabstops. Since Elastic tabstops is controlled independently for each document, it maintains a list of Scintilla document pointers of open documents mapped to some control information, which includes whether Elastic tabstops is enabled and, if it is, data about the tab layout. So when Columns++ gets those notifications, it checks some mask information in the notification and returns if it isn’t interested, then gets the Scintilla control information from the notification, does a [SCI_GETDOCPOINTER](https://www.scintilla.org/ScintillaDoc.html#SCI_GETDOCPOINTER), and looks up the document. If it’s not in the internal table, or if it is in the internal table and Elastic tabstops is disabled, it returns without doing anything else.

So, if none of your open tabs have Elastic tabstops enabled, Columns++ is crashing somewhere between getting the notifications and determining that it doesn’t need to process them, or it is wrongly determining that it should process them. I’ll have to think about how to put in some extra checks to diagnose what is happening there.

Thank you for your patience.

**Comment by daddel80** [comment]
It looks like you've found the end where you need to pull. That sounds like a plan. I hope you get it under control. Just for the sake of completeness, here is the error message I get after the notification error when I select Elastic Tabstop Menuepoint.
![image](https://github.com/Coises/ColumnsPlusPlus/assets/53190206/87084bbf-2d30-4a63-b898-778001f53981)

**Comment by Coises** [comment]
@daddel80

I’ve added “DIAGNOSTIC” binaries to the [0.7.2-alpha release](https://github.com/Coises/ColumnsPlusPlus/releases/tag/v0.7.2-alpha). The code is in the [diagnostic](https://github.com/Coises/ColumnsPlusPlus/tree/diagnostic) branch of this repository.

If you would, I’d like you to install these in place of the 0.7.2 release. In the cases where you were getting a message about a crash during an SCNotification call, you should now first get a message box from Columns++ with a trace. If you press Ctrl+C while the box is active, that will copy the text to the clipboard. If you would then paste that into a comment here, it might help me figure out where something is going wrong.

Thank you for your help and your patience.

**Comment by daddel80** [comment]
I'm on a trip over the Weekend. I will install it on Monday. The "good" thing is that yesterday I had the same issue once. So there is a good chance to catch ithe bug.

**Comment by daddel80** [comment]
Here we go.... 

---------------------------
Columns++: Error trace
---------------------------
getDocument sending GetDirectPointer to activeScintilla = 3737140
getDocument calling SetFnPtr(140699085532496,1615858999504).
getDocument calling DocPointer.
getDocument checking if documents contains docptr = 1616369309888
getDocument getting document data address.
getDocument returning document data address 1615859507112
Exiting scnModified; Elastic tabs are not enabled.
Calling scnUpdateUI.
Entered scnUpdateUI; scnp->updated is 3
Entered getDocument with scnp = 122556491280
getDocument sending GetDirectPointer to activeScintilla = 3737140
getDocument calling SetFnPtr(140699085532496,1615858999504).
getDocument calling DocPointer.
getDocument checking if documents contains docptr = 1616369309888
getDocument getting document data address.
getDocument returning document data address 1615859507112
scnUpdateUI calling syncFindButton.
Exiting scnUpdateUI: Elastic tabstops not enabled.
Calling scnModified.
Entered scnModified; scnp->modificationType is 2064
Entered getDocument with scnp = 122556481328
getDocument sending GetDirectPointer to activeScintilla = 3737140
getDocument calling SetFnPtr(140699085532496,1615858999504).
getDocument calling DocPointer.
---------------------------

**Comment by daddel80** [comment]
next one ...

getDocument calling DocPointer.
getDocument checking if documents contains docptr = 2346961035136
getDocument getting document data address.
getDocument returning document data address 2346961861000
Exiting scnModified; Elastic tabs are not enabled.
Calling scnUpdateUI.
Entered scnUpdateUI; scnp->updated is 3
Entered getDocument with scnp = 576591996560
getDocument sending GetDirectPointer to activeScintilla = 5309828
getDocument calling SetFnPtr(140699085532496,2346451321488).
getDocument calling DocPointer.
getDocument checking if documents contains docptr = 2346961035136
getDocument getting document data address.
getDocument returning document data address 2346961861000
scnUpdateUI calling syncFindButton.
Exiting scnUpdateUI: Elastic tabstops not enabled.
Calling scnUpdateUI.
Entered scnUpdateUI; scnp->updated is 8
Calling scnModified.
Entered scnModified; scnp->modificationType is 2064
Entered getDocument with scnp = 576591986608
getDocument sending GetDirectPointer to activeScintilla = 5309828
getDocument calling SetFnPtr(140699085532496,2346451321488).
getDocument calling DocPointer.

**Comment by Coises** [comment]
@daddel80 Thank you so much. I think I see the problem. If I’m correct about what it is, the fix won’t be difficult. I expect to have a new version available later today or tomorrow.

**Comment by daddel80** [comment]
> @daddel80 Thank you so much. I think I see the problem. If I’m correct about what it is, the fix won’t be difficult. 

Good to hear. I have installed latest Diagnostic Version 0.7.2.2 now.

**Comment by daddel80** [comment]
I can confirm that your version is stable now. I found the reason on my side. SCI_GETTAG produced a Generic failure i had to fix.

**Comment by Coises** [comment]
@daddel80 Thank you for your help with this. Improved exception handling  (without the diagnostic trace) and a couple other unrelated fixes will be in version 0.7.3.
