### ISSUE TITLE
Search crashes with zero length multi-edit carets

### ISSUE THREAD

**Issue by astewart77** [Coises/ColumnsPlusPlus#13]
n++ v8.5.8 Columns++ v0.7.4

If a vertical rectangle of zero width is selected, Search prompts to extend
the rectangle and the Search works.

If several multi-edit carets are set with zero length selections,
no extend prompt occurs and Search stops responding.

If the multi-edit selections are extended manually before Search,
the Search succeeds.

**Comment by Coises** [comment]
@astewart77 Thank you for catching this and describing it perfectly.

It is beyond the scope of what I intended Columns++ to do to try to extend multiple selections, but going unresponsive is not acceptable; [v0.7.5-alpha](https://github.com/Coises/ColumnsPlusPlus/releases/tag/v0.7.5-alpha) addresses this issue by showing a message that a search region could not be constructed from the selection when the user attempts to initiate a search with a multiple selection in which all selections are empty.
