### ISSUE TITLE
Quick installer (v1.0.1) is detected as a threat by Windows Defender

### ISSUE THREAD

**Issue by jamiescottie1** [Coises/ColumnsPlusPlus#17]
Downloading the quick installer for version 1.0.1 ("ColumnsPlusPlus-1.0.1.exe") is recognized as a threat by Windows Defender. While I don't necessarily believe that a virus is being distributed with malicious intent, this still at least prevents the the plugin from being installed. See attached the details given by Windows Defender:
![Screenshot 2023-12-19 111948](https://github.com/Coises/ColumnsPlusPlus/assets/47101998/b1f39999-4603-4c43-9be9-993629870223)

**Comment by Coises** [comment]
Thank you for your report.

There may be very little I can do about this. “Wacapew.C!ml” is a generic description which is apparently applied to “suspicious” installers; to avoid telling “the bad guys” how to evade detection, the makers of malware scanners can’t tell the rest of us how to avoid triggering false positives, either.

The most direct ways of avoiding this kind of flagging require paying a yearly fee for a personal code signing certificate or being a business holding an enhanced code signing certificate. Even those don’t always stop false positives. At some point I will try building a more traditional (and complex) installer, but that will take some time and is not guaranteed to avoid the false positive.

In the meantime, workarounds are:

1. Click “Learn more”; there should be an option to run the installer anyway, unless you (or the administrator of the machine, if that’s not you) have disabled the ability to do that.
2. Install manually, as described [here](https://github.com/Coises/ColumnsPlusPlus#installation).
3. Wait for the next release of Notepad++, when some version of Columns++ should be included in Plugins Admin.

I’m going to close this for now as “deferred”; the condition reported is not user-friendly, but it will take some time and effort to attempt a fix, and that fix might be temporary or unsuccessful in any case. Once Columns++ is included in Plugins Admin in Notepad++, most users will install it that way and probably ignore updates until Notepad++ is updated. There is no good solution to this for a developer who is not a “professional” working for a recognized company or at least able to justify the cost of code signing certificates.
