### ISSUE TITLE
Cursor moves to unexpected positions on vertical movement after entering elastic tabstops

### ISSUE THREAD

**Issue by Edsploration** [Coises/ColumnsPlusPlus#18]
The cursor sometimes jumps ahead one or more characters when moving vertically after pressing `tab`.

![elastic tabs cursor bug](https://github.com/Coises/ColumnsPlusPlus/assets/1069774/98ed76c7-9ad4-47d0-bb4e-1f7257fa39ef)

The cursor seems to move based on the visual position it would have if regular tabs were used, which makes me think this is just the native behavior of Notepad++, and it may be difficult to correct in the plugin. But on the other hand, it does move correctly from a preexisting elastic tabstop. It seems to be only when `tab` is followed immediately by `up arrow` or `down arrow` that this movement occurs.

Here is a spliced animation of the expected behavior:
![elastic tabs cursor expected behavior](https://github.com/Coises/ColumnsPlusPlus/assets/1069774/2c781a30-e3a3-4094-a441-6bf44550bbeb)

Perhaps the Col number disagreeing with the visual location of the cursor is related? Since the Col number depends on tab size setting, I'd hope it could also depend on the elastic tabstops setting.

And thank you for making this amazing plugin! I've been wanting something like elastic tabstops for years and I just found the term today.

**Comment by Coises** [comment]
Thank you for the report and your kind words. I can reproduce this. I’m not yet sure whether I can fix it, but I will try.

**Comment by Coises** [comment]
@Edsploration

Thank you again for your clear description of this issue. It turned out to be a pretty simple omission on my part. The change has little risk of introducing any new problems, so I’ve gone ahead and made a new release, [v1.0.3](https://github.com/Coises/ColumnsPlusPlus/releases/tag/v1.0.3). I’ll set it as latest/stable in a few days if nothing unexpected happens.

I’ll close this, as it resolves the issue in my tests; please comment and re-open if you find that it has not fixed the problem for you, or if there are unexpected side-effects.

**Comment by Edsploration** [comment]
Fantastic! It looks like it still happens after only a single tab is entered without having any other adjacent ones, but I'm more than satisfied.

**Comment by Coises** [comment]
@Edsploration 
> Fantastic! It looks like it still happens after only a single tab is entered without having any other adjacent ones, but I'm more than satisfied.

I missed that at first, but I see it now. Thank you for pointing it out.

While attempting to reproduce it, I found another misbehavior as well: "Minimum space between elastic tabs” is sometimes ignored, under somewhat complicated circumstances. I have a hunch the two might be related, but I’m not sure of that. I’m going to leave this issue closed and treat the remaining incorrect behavior as a new issue.

**Comment by Coises** [comment]
@Edsploration 
> It looks like it still happens after only a single tab is entered without having any other adjacent ones

I think this is fixed now. Use the the [1.0.3.1 binaries](https://github.com/Coises/ColumnsPlusPlus/releases/tag/v1.0.3.1) or the Quick Installer. Let me know if problems persist.

**Comment by Edsploration** [comment]
Running 1.0.3.1 now and it works perfectly! It is a joy to use!
