### ISSUE TITLE
Caret column not preserved when Elastic Tabstops enabled

### ISSUE THREAD

**Issue by ahmetsait** [Coises/ColumnsPlusPlus#25]
Example:
```
abcde| <- Caret
a
```
Press down arrow:
```
abcde
a|
```
Press up arrow:
```
a|bcde
a
```
The caret goes back to its original position when elastic tabstops are disabled:
```
abcde|
a
```

> Notepad++ v8.7   (64-bit)
Build time : Sep 17 2024 - 17:06:31
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Home Single Language (64-bit)
OS Version : 22H2
OS Build : 19045.4894
Current ANSI codepage : 1254
Plugins : 
    ColumnsPlusPlus (1.1.2)
    ComparePlus (1.2)
    DSpellCheck (1.5)
    Explorer (1.9.9)
    GitSCM (1.4.9.1)
    HexEditor (0.9.12)
    mimeTools (3.1)
    nppAutoDetectIndent (2.3)
    NppConverter (4.6)
    nppcrypt (1.0.1.6)
    NppEditorConfig (0.4)
    NppExec (0.8.8)
    NppExport (0.4)
    NppMenuSearch (0.9.6)
    NppQrCode64 (0.0.0.2)
    OpenSelection (1.1.3)
    PoorMansTSqlFormatterNppPlugin (1.6.13.31508)
    Remove Duplicate Lines (1.3)
    SQLinFormNpp64 (6.24.7.15)
    SurroundSelection (1.4.1)
    zoomdisabler_x64 (1.2)

**Comment by Coises** [comment]
@ahmetsait 

Thank you for the report. I can reproduce this, and I will try to correct it.

I suspect this is somehow related to my fix for Issue #18; I don’t know yet if it can be corrected without re-introducing that problem.

**Comment by Coises** [comment]
@ahmetsait

[Columns++ version 1.1.3](https://github.com/Coises/ColumnsPlusPlus/releases/tag/v1.1.3) should fix this. If you would, when you have a chance, confirm whether this resolves the problem you had. Also, let me know if you observe any other incorrect behavior.

Thank you again for identifying and clearly describing this problem.

**Comment by ahmetsait** [comment]
@Coises Thanks a lot for the quick fix!
I can confirm that the issue is resolved in `v1.1.3` and everything seems to be in order for now.
I use Notepad++ with elastic tabstops enabled so I will open a new issue if I encounter any strange behavior.
